---
title: "Optimizing mechanical properties"
output: 
  pdf_document: 
    keep_tex: true
date: "2024-12-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dev = "png",
                      dpi = 300)

library(tidyverse)
library(ggnewscale)
library(AlgDesign)
theme_set(theme_bw()+
            theme(text=element_text(size = 14),
                  legend.box.margin = margin(-10,-10,-10,-10),
                  legend.position = "none",
                  legend.text = element_text(size=12)))
library(gridExtra)
library(nloptr)
library(latex2exp)
library(collapse)
library(Matrix)
library(rdist)
library(hetGP)
```


## Import Data and Initial Set Up

```{r}
metals <- c("Mo","Nb","Ta","V","W")
properties <- c("log_max_strain",
                "bc_1","bc_2","bc_3","bc_4")
n_prop <- length(properties)
n_dim <- length(metals)



dat_ss_c <- rio::import(here::here("Data",
                                 "ss_all_ort_coefs_c_uns.csv"))

dat_ss_c <- as_tibble(dat_ss_c)

dat_ss_c <- dat_ss_c%>%
            filter(!(alloy %in% metals))%>%
            mutate(id_row = row_number())

dat_ss_t <- rio::import(here::here("Data",
                                 "ss_all_ort_coefs_t_uns.csv"))

dat_ss_t <- as_tibble(dat_ss_t)

dat_ss_t <- dat_ss_t%>%
            filter(!(alloy %in% metals))%>%
            mutate(id_row = row_number())


```


```{r}
source(here::here("Functions",
                    "mv_imspe_funs.R"))

source(here::here("Functions",
                    "kernel_funs.R"))

source(here::here("Functions",
                    "coords_tranform_funs.R"))

source(here::here("Functions",
                    "prediction_sampling_funs.R"))

source(here::here("Functions",
                    "orth_basis_funs.R"))

source(here::here("Functions",
                    "rm_mvgps_mat_mu_pred_functions.R"))
```



### Modify into sets

```{r}
dat_ss_all <- dat_ss_t%>%
                filter(!(alloy %in% metals))%>%
                mutate(type = "t")%>%
                bind_rows(dat_ss_c%>%
                            mutate(type ="c"))%>%
                unite("alloy_id",
                      Mo:W,remove = FALSE)%>%
                arrange(alloy_id, rep, type)#%>%
                  #filter(! alloy %in% metals)

dat_ss_fil <- dat_ss_all%>%
              ungroup()%>%
              group_by(alloy_id)%>%
              arrange(desc(rep))%>%
              slice_head(n=1)
```




### Parameters

```{r}
joint_cov <- het_sv <-joint_ls_gp <- F
max_train_iters <- 10
scale_vars <- "after"
al_steps <- 6
mean_opt <- "cons" # pol for polynomial splines

dat_type <- "binodd" #binodd_ter
date_exp <- "25-04-25"

exp_name <- paste("train",
                  dat_type,
                  mean_opt,
                  date_exp,
                  sep = "_")


ini_seed <- 233545
verbose <- F

ini_prev_mod <- T
cov_type = "Matern5_2" #"Gaussian", "Matern5_2", "Matern3_2"


cor_fun_test <- function(theta, D_mat) general_cor_fun(theta = theta,
                                                       D_mat = D_mat,
                                                       kernel_fun = matern_5_2_fun)
```



## Prepare the data

```{r}
dat_ss_fil <- dat_ss_fil%>%
  mutate(elements= (Mo>0) + (Nb>0) + (Ta>0) + (V>0) + (W>0))
  
```

```{r}
## Training
temp <- dat_ss_fil%>%
  ungroup()%>%
  filter(elements == 2,
         round(pmax(Mo,Nb,Ta,V,W),1) %in% c(0.1,0.3,0.5,0.7,0.9) 
         )%>%
  arrange(alloy_cnt)

if(dat_type == "binodd_ter"){
  temp2 <- dat_ss_fil%>%
  ungroup()%>%
  filter(elements == 3)
  
  temp <- bind_rows(temp, temp2)
}

id_train <- temp$alloy_cnt

dat_ss_train <- dat_ss_fil%>%
      filter((alloy_cnt %in% id_train))%>%
  arrange(alloy_cnt)



dat_train <- dat_ss_all%>%
      filter(alloy_cnt %in% id_train)%>%
      arrange(alloy_cnt)%>%
                  pivot_longer(cols = all_of(properties),
                               names_to = "property",
                               values_to = "val_true")

dat_train_B <- dat_train%>%
    group_by(alloy_cnt, rep)%>%
  slice_head(n=1)
    
dat_train_c <- dat_train%>%
      filter(type == "c")
    
dat_train_t <- dat_train%>%
      filter(type == "t")
```


```{r}
prop_b <- properties
prop_b[1] <- "lms"
Basis_X <- Basis_X_all <- NULL


if(mean_opt == "pol"){
  Basis_X <- create_poly_basis(as.matrix(dat_ss_train[,metals]),
                                   n_out = n_prop,
                                   prop_names = prop_b,
                                   sparse_mat = T,
                               degree = 1,
                               omit_last_var = T,
                                   var_names = metals)

  Basis_X_all <- create_poly_basis(as.matrix(dat_train_B[,metals]),
                                     n_out = n_prop,
                                     prop_names = prop_b,
                                     sparse_mat = T,
                                 degree = 1,
                                 omit_last_var = T,
                                     var_names = metals)
}
    
y_train_c <- as.vector(dat_train_c$val_true)
Y_train_c <- matrix(y_train_c,
                        ncol = n_prop,
                        byrow = T)
    
y_train_t <- as.vector(dat_train_t$val_true)
    
Y_train_t <- matrix(y_train_t,
                        ncol = n_prop,
                        byrow = T)
    
a_reps <- dat_ss_all%>%
      arrange(alloy_cnt)%>%
      filter((alloy_cnt %in% id_train))%>%
                ungroup()%>%
                group_by(alloy_cnt)%>%
                tally()
    
a_reps <- a_reps$n/2

X_train <- as.matrix(dat_ss_train[,metals])
```





```{r}
dat_cand <- dat_ss_fil%>%
  filter(elements > 2,
         rep > 1)

ids_cand <- dat_cand$alloy_cnt

dat_ss_c_cand <- dat_ss_c%>%
                filter(alloy_cnt %in% ids_cand)

dat_ss_t_cand <- dat_ss_t%>%
                filter(alloy_cnt %in% ids_cand)
```


```{r}
X_ini <- as.matrix(dat_ss_train[,metals])
X_ini_B <- as.matrix(dat_train_B[,metals])

X_cand_ini <- as.matrix(dat_cand[,metals])

X_cand_ini_B <- as.matrix(dat_ss_c_cand[,metals])

dat_ss_c_cand <- dat_ss_c_cand%>%
                  pivot_longer(cols = all_of(properties),
                               names_to = "property",
                               values_to = "val_true")

dat_ss_t_cand <- dat_ss_t_cand%>%
                  pivot_longer(cols = all_of(properties),
                               names_to = "property",
                               values_to = "val_true")

```

### Active Learning Steps

```{r}
set.seed(ini_seed)
test_pX_bin <- gen.mixture(levels = 3,
                  vars = metals)
    
idp <- which(sapply(1:nrow(test_pX_bin), 
                        function(i) max(test_pX_bin[i,]) == 1 ))
test_pX_bin <- as.matrix(test_pX_bin[-idp,])
    
test_pX <- gen.mixture(levels = 4,
                  vars = metals)
test_pX <- rbind(as.matrix(test_pX),
                     test_pX_bin)
idp <- which(sapply(1:nrow(test_pX), function(i) max(test_pX[i,]) == 1 ))
    
pX_edge <- test_pX[idp,]
    
test_pXB <- rbind(test_pX[-idp,],
                     test_pX[idp,])
test_pX <- test_pX[-idp,]
    
n_ed <- length(metals)

y_ini_c <- as.vector(dat_train_c$val_true)

    
y_ini_t <- as.vector(dat_train_t$val_true)

    
a_reps <- dat_ss_all%>%
      arrange(alloy_cnt)%>%
      filter((alloy_cnt %in% id_train))%>%
                ungroup()%>%
                group_by(alloy_cnt)%>%
                tally()
    
a_reps <- a_reps$n/2


#homogeneous solution
Y_train_c <- matrix(y_ini_c,
                        ncol = n_prop,
                        byrow = T)
  
Y_train_t <- matrix(y_ini_t,
                          ncol = n_prop,
                          byrow = T)
  
result_stats_c <- compute_mean_var_fun(Y = Y_train_c,
                                     a_mult = a_reps,
                                     rescale_y = scale_vars)

ini_hom_c <- ini_pars_hom_fun(result_stats_c, 
                                  n_dim = n_dim,
                                  log_bounds = log(c(1e-2,5,50)))
    
result_stats_t <- compute_mean_var_fun(Y = Y_train_t,
                                     a_mult = a_reps,
                                     rescale_y = scale_vars)

ini_hom_t <- ini_pars_hom_fun(result_stats_t,
                                  n_dim = n_dim,
                                  log_bounds = log(c(1e-2,5,50)))
    
np_id_h <- NULL
```

Runs in about 15 minutes

```{r}
for(iter in 0:5){
  
  file_name <- paste0(exp_name,"_AL_iter_",iter,".RData")
  file_path <- here::here("Trained Models",file_name)
  
  
  X_train <-X_ini
  X_cand <- X_cand_ini
  X_cand_B <- X_cand_ini_B
  X_train_B <- X_ini_B
  y_train_c <- y_ini_c
  y_train_t <- y_ini_t
  
  if(iter > 0){
    idx <- 1:3 + (np_id_h[1]-1) *3
    idx_b <- 1:(3*n_prop) + (np_id_h[1]-1) *(3*n_prop) 
    
    if(iter > 1){
      for(j in 2:iter){
        idx <- c(idx, 1:3 + (np_id_h[j]-1) *3)
        idx_b <- c(idx_b, 1:(3*n_prop) + (np_id_h[j]-1) *(3*n_prop))
      } 
    }
    
    X_cand <- X_cand_ini[-np_id_h,]
    X_cand_B <- X_cand_ini_B[-idx,]
    
    y_train_c <- c(y_train_c, 
                   dat_ss_c_cand$val_true[idx_b])
    y_train_t <- c(y_train_t, 
                   dat_ss_t_cand$val_true[idx_b])
    a_reps <- c(a_reps, 3)
    X_train <- rbind(X_ini,
                     X_cand_ini[np_id_h,])
    
    X_train_B <- rbind(X_ini_B,
                     X_cand_ini_B[idx,])
    
  }
  Y_train_c <- matrix(y_train_c,
                        ncol = n_prop,
                        byrow = T)
  
      
  Y_train_t <- matrix(y_train_t,
                          ncol = n_prop,
                          byrow = T)
  
  
  Basis_X <- Basis_X_all <- NULL
  
  if(mean_opt == "pol"){
    Basis_X <- create_poly_basis(X_train,
                                   n_out = n_prop,
                                   prop_names = prop_b,
                                   sparse_mat = T,
                               degree = 1,
                               omit_last_var = T,
                                   var_names = metals)

  Basis_X_all <- create_poly_basis(X_train_B,
                                     n_out = n_prop,
                                     prop_names = prop_b,
                                     sparse_mat = T,
                                 degree = 1,
                                 omit_last_var = T,
                                     var_names = metals)
  }


  if(file.exists(file_path)){
    load(file_path)
  }else{
    ## Training
    message(paste("Iteration", iter))
    message(Sys.time())
    
    #PX
    ini_sol_h <- ini_hom_c$ini
    if(iter>0) ini_hom_c <- update_ini_pars_fun(mod_hom_c$opt_sol$solution,
                                     ini_hom_c)
    
    mod_hom_c <- fit_mvgp_sv_fun(Y = Y_train_c,
                            X = X_train,
                            X_pred = Basis_X,
                            X_pred_all = Basis_X_all,
                            a_mult = a_reps,
                            cor_fun = cor_fun_test,
                            joint_cov = joint_cov,
                            het_sv = F,
                            lb = ini_hom_c$lb,
                            ub = ini_hom_c$ub,
                            ini_pars = ini_hom_c$ini,
                            joint_ls_gp = joint_ls_gp,
                            max_it =max_train_iters,
                            rescale_y = scale_vars,
                            rs = result_stats_c,
                            verbose = verbose)
    
    eval_log_c <- fit_mvgp_sv_fun(Y = Y_train_c,
                        X = X_train,
                        X_pred = Basis_X,
                            X_pred_all = Basis_X_all,
                        a_mult = a_reps,
                        cor_fun = cor_fun_test,
                        joint_cov = joint_cov,
                        het_sv = F,
                        ini_pars = mod_hom_c$opt_sol$solution,
                        joint_ls_gp = joint_ls_gp,
                        opt = F,
                        rescale_y = scale_vars,
                            verbose = verbose)
    
    
    if(iter>0) ini_hom_t <- update_ini_pars_fun(mod_hom_t$opt_sol$solution,
                                     ini_hom_t)
    
    mod_hom_t <- fit_mvgp_sv_fun(Y = Y_train_t,
                            X = X_train,
                            X_pred = Basis_X,
                            X_pred_all = Basis_X_all,
                            a_mult = a_reps,
                            cor_fun = cor_fun_test,
                            joint_cov = joint_cov,
                            het_sv = F,
                            lb = ini_hom_t$lb,
                            ub = ini_hom_t$ub,
                            ini_pars = ini_hom_t$ini,
                            joint_ls_gp = joint_ls_gp,
                            rescale_y = scale_vars,
                            rs = result_stats_t,
                            verbose = verbose)
    
    
    eval_log_t <- fit_mvgp_sv_fun(Y = Y_train_t,
                            X = X_train,
                            X_pred = Basis_X,
                            X_pred_all = Basis_X_all,
                            a_mult = a_reps,
                            cor_fun = cor_fun_test,
                            joint_cov = joint_cov,
                            het_sv = F,
                            ini_pars = mod_hom_t$opt_sol$solution,
                            joint_ls_gp = joint_ls_gp,
                            max_it =max_train_iters,
                            opt = F,
                            rescale_y = scale_vars,
                            verbose = verbose)
    
    ### Heterogeneous solution
    
    message("Heterogeneous Tension")
    message(Sys.time())
  
    pen_par <- F
    am_px <- rep(1,nrow(test_pXB))
    nrPx <- nrow(test_pXB)
    nrt <- nrow(X_train)
    
    idx_1 <- which(duplicated(rbind(test_pXB,X_train)))
    idx_2 <- which(duplicated(rbind(X_train, test_pXB)))
    am_px[idx_2 - nrt] <- a_reps[idx_1 - nrPx]
    
    if(iter >0){
      ini_sol_t <- update_ini_pars_fun(mod_t$opt_sol$solution,
                                 ini_sol = ini_sol_t)
    }else{
      ini_sol_t <- pars_hom_to_het_reg(mod_hom_t$opt_sol$solution,
                               n_properties = n_prop,
                               pX = test_pX,
                               X = X_train,
                               edge_locs = pX_edge,
                               var_mat = result_stats_t$var_mat,
                               idx_use = result_stats_t$idx,
                                cor_fun = cor_fun_test,
                                phi_h = attr(eval_log_t,"psi"),
                               log_mult = c(-log(2),log(1.5), log(2)),
                               log_bounds =c(log(1e-3),
                                         log(10),
                                         log(10))
                               )
    }
    
    
    
    mod_t <- fit_mvgp_sv_fun(Y = Y_train_t,
                        X = X_train,
                        X_pred = Basis_X,
                        X_pred_all = Basis_X_all,
                        a_mult = a_reps,
                        pX = test_pXB,
                        a_mult_px = am_px,
                        n_edge = n_ed,
                        cor_fun = cor_fun_test,
                        joint_cov = joint_cov,
                        het_sv = T,
                        ini_pars = ini_sol_t$ini,
                        ub = ini_sol_t$ub,
                        lb = ini_sol_t$lb,
                        penalty = pen_par,
                        joint_ls_gp = joint_ls_gp,
                        max_it = max_train_iters,
                        rescale_y = scale_vars,
                        rs = result_stats_t,
                            verbose = verbose)
    
    
    message("Heterogeneous Compression")
    message(Sys.time())
    
    
    if(iter>0){
      ini_sol_c <- update_ini_pars_fun(mod_c$opt_sol$solution,
                                 ini_sol = ini_sol_c)
    }else{
      ini_sol_c <- pars_hom_to_het_reg(mod_hom_c$opt_sol$solution,
                           n_properties = n_prop,
                           pX = test_pX,
                           X = X_train,
                           edge_locs = pX_edge,
                           var_mat = result_stats_c$var_mat,
                           idx_use = result_stats_c$idx,
                            cor_fun = cor_fun_test,
                            phi_h = attr(eval_log_c,"psi"),
                           log_mult = c(-log(2),log(1.5), log(2)),
                           log_bounds =c(log(1e-3),
                                         log(10),
                                         log(10))
                           )
    }
    
    

    mod_c <- fit_mvgp_sv_fun(Y = Y_train_c,
                            X = X_train,
                            X_pred = Basis_X,
                            X_pred_all = Basis_X_all,
                            a_mult = a_reps,
                            pX = test_pXB,
                            a_mult_px =am_px,
                            n_edge = n_ed,
                            cor_fun = cor_fun_test,
                            joint_cov = joint_cov,
                            het_sv = T,
                            ini_pars = ini_sol_c$ini,
                            ub = ini_sol_c$ub,
                            lb = ini_sol_c$lb,
                            penalty = pen_par,
                            joint_ls_gp = F,
                            max_it = max_train_iters,
                            rescale_y = scale_vars,
                            rs = result_stats_c,
                            verbose = verbose)
    
    ## Prediction object
    
    test_pred_obj_t <- construct_pred_obj_fun(pars = mod_t$opt_sol$solution,
                                        X = X_train,
                                        Y_mat = mod_t$Y,
                                        y_bar = mod_t$y_bar,
                                        X_pred = Basis_X,
                                        X_pred_all = Basis_X_all,
                                        pX = test_pXB,
                                        n_edge = n_ed,
                                        n_properties = n_prop,
                                        a_mult = a_reps,
                                        a_mult_pX = am_px,
                                        cor_fun_gp = cor_fun_test,
                                        rescale_y = mod_t$rs_y,
                                        rs_mean = mod_t$rs_mean,
                                        rs_mult = mod_t$rs_mult)

    test_pred_obj_c <- construct_pred_obj_fun(pars = mod_c$opt_sol$solution,
                                            X = X_train,
                                            X_pred = Basis_X,
                                            X_pred_all = Basis_X_all,
                                            Y_mat = mod_c$Y,
                                            y_bar = mod_c$y_bar,
                                            pX = test_pXB,
                                            n_edge = n_ed,
                                            n_properties = n_prop,
                                            a_mult = a_reps,
                                            a_mult_pX = am_px,
                                            cor_fun_gp = cor_fun_test,
                                            rescale_y = mod_c$rs_y,
                                            rs_mean = mod_c$rs_mean,
                                            rs_mult = mod_c$rs_mult)
    
    pol<- list(po_t = test_pred_obj_t,
                          po_c = test_pred_obj_c)
    
    message("Next Point")
    message(Sys.time())
    
    next_point <- IMSPE_MV_batch_search(pred_obj = pol,
                                        Xcand = X_cand[,metals],
                                        seed = np_seed,
                                        n_reps_batch = 3,
                                        n_block = 2,
                                        cv = F,
                                        n_cores = 3)
    
    save(result_stats_c,result_stats_t,
      ini_sol_c,ini_sol_t,
     mod_c,mod_hom_c,
     mod_hom_t,mod_t,
     pol,
     next_point,
     file = file_path)
  }
  
  np_id_h <- c(np_id_h, 
               which.min(rdist::cdist(next_point$best_obj$par,X_cand_ini)))
  
}


```

```{r}
save(np_id_h,
     file = here::here("Trained Models",
                       "AL_np_h_int_m52.RData"))

```



## Plot Prediction Accuracy Acctive Learning

```{r}
props <- c("ultimate_stress","ultimate_strain",
           "toughness","young_mod")

prop_ltx <- unname(TeX(c("$\\sigma_u$","$\\epsilon_u$",
                         "$U_T$","$E$")))
```

```{r}
dat_cand_2 <- dat_ss_fil%>%
  filter(elements > 2,
         rep == 1)

id_test <- dat_cand$alloy_cnt
id_test <- id_test[-np_id_h]
id_test <- c(id_test,dat_cand_2$alloy_cnt)

dat_ss_test <- dat_ss_fil%>%
      filter(alloy_cnt %in% id_test)%>%
  arrange(alloy_cnt)

dat_ss_test_B <- dat_ss_fil%>%
    group_by(alloy_cnt, rep)%>%
  slice_head(n=1)


X_test <- dat_ss_test

dat_sim <- dat_ss_all%>%
  filter(alloy_cnt %in% id_test)%>%
  mutate(ultimate_stress = exp(log_max_stress),
         ultimate_strain = exp(log_max_strain),
         Test = ifelse(type == "c",
                       "Compression",
                       "Tension"))%>%
  pivot_longer(cols= all_of(props),
               values_to = "val",
               names_to = "property")

temp <- dat_ss_fil%>%
  filter(elements == 2,
         round(pmax(Mo,Nb,Ta,V,W),1) %in% c(0.2,0.4,0.6,0.8) 
         )%>%
  ungroup()%>%
  arrange(alloy_cnt)

id_test_bin <- temp$alloy_cnt
  
dat_ss_test_bin <- dat_ss_fil%>%
      filter(alloy_cnt %in% id_test_bin)%>%
  arrange(alloy_cnt)

dat_sim_bin <- dat_ss_all%>%
  filter(alloy_cnt %in% id_test_bin)%>%
  mutate(ultimate_stress = exp(log_max_stress),
         ultimate_strain = exp(log_max_strain),
         Test = ifelse(type == "c",
                       "Compression",
                       "Tension"))%>%
  pivot_longer(cols= all_of(props),
               values_to = "val",
               names_to = "property")
```


```{r}
st <- Sys.time()

mod_names <- 0:5

dat_mu <- dat_lb <- dat_ub <- dat_var <- dat_nug <- dat_pm <- vector(mode = "list", 
                                                                     length = 2)
imspe_t <- imspe_c <- rep(0, length(mod_names))

k <- 0
BX <- NULL

if(mean_opt == "pol"){
  BX <- create_poly_basis(as.matrix(dat_ss_test[,metals]),
                                   n_out = n_prop,
                                   prop_names = prop_b,
                                   sparse_mat = T,
                               degree = 1,
                               omit_last_var = T,
                                   var_names = metals)
}

for(i in 1:length(mod_names)){
  file_name <- paste0(exp_name,
                      "_AL_iter_",i-1,".RData")
for(j in 1:2){
    
  k <- k + 1
    message(Sys.time())
     results <- import_predict_mod_het_gp_sampling_fun(newX = as.matrix(X_test[,metals]),
                                           Xdesign = X_test[,c(metals,"alloy_cnt")],
                                           newX_pred = BX,
                                           file_path = here::here("Trained Models",
                                                                  file_name),
                                           step_id = mod_names[i],
                                           mod_id = j,
                                           rseed = 1323,
                                           n_samples = 1e4,
                                           prop_names = properties)
      gc()
     dat_mu[[k]] <- results$gp_mu
     dat_var[[k]] <- results$gp_var
     dat_nug[[k]] <- results$gp_nug
     dat_pm[[k]] <- results$mp_mean
     dat_lb[[k]] <- results$mp_lb
     dat_ub[[k]] <- results$mp_ub
     
     if(j > 1){
       imspe_c[i] <- results$imspe
     }else{
       imspe_t[i] <- results$imspe
     }
}
}

dat_mu <- bind_rows(dat_mu)
dat_var <- bind_rows(dat_var)
dat_nug <- bind_rows(dat_nug)
dat_pm <- bind_rows(dat_pm)
dat_lb <- bind_rows(dat_lb)
dat_ub <- bind_rows(dat_ub)

ft <- Sys.time()
print(ft - st)
```



```{r}
dat_comp <- dat_pm%>%
           pivot_longer(cols= all_of(props),
               values_to = "pred",
               names_to = "property")%>%
            inner_join(dat_sim%>%
                         select(alloy_cnt,Test,property,val)%>%
                         group_by(alloy_cnt,Test,property)%>%
                         summarise(val = mean(val)),
                       by = join_by(alloy_cnt,Test,property))

```


```{r acc_mods_al, fig.height=5, fig.width=7}
p1 <- dat_comp%>%
  mutate(rer = (pred-val)/val,
         Step = factor(Step,
                       levels = mod_names),
         property = factor(property,
                           levels = props,
                           labels = prop_ltx))%>%
  ggplot(aes(x= property,
             y= 100*rer,
             colour = Step))+
  geom_boxplot()+
  scale_color_brewer("Iteration", palette = "Dark2")+
  scale_x_discrete(labels = prop_ltx)+
  facet_wrap(~Test,
             ncol = 1, 
             scales = "free")+
  labs(y = "Relative Error (%)",
       x = "Property",
       title="Accuracy on Quaternaries GP Model with Constant Mean")+
  theme(legend.position = "bottom",
        axis.text.x = element_text(size = 12),
        legend.text = element_text(size=10),
        legend.title = element_text(size =10))+ 
    guides(colour = guide_legend(nrow = 1))

p1
```




IMSPE

```{r}
tibble(Iteration = 0:5,
       IMSPE_C = round(imspe_c,2),
       IMSPE_T = round(imspe_t,2),
       IMSPE = round(imspe_c + imspe_c,2))
```




## Plot Predictions Last Model for Even Binaries


```{r}
alloys_in <- c("V","W", "VW")

x <-seq(0.01,0.99, by = 0.01)
X_vw <- tibble(Mo = 0,
                   Nb = 0,
                   Ta = 0,
                   V = x,
                   W = 1-x)
X_vw_pred <- as.matrix(X_vw)

X_vw <- X_vw%>%
  unite("alloy_id",
        Mo:W,
        remove = FALSE)%>%
  mutate(id = row_number())

if(mean_opt == "pol"){
  BX <- create_poly_basis(X_vw_pred,
                                   n_out = n_prop,
                                   prop_names = prop_b,
                                   sparse_mat = T,
                               degree = 1,
                               omit_last_var = T,
                                   var_names = metals)
}

results_bin <- import_predict_mod_het_gp_sampling_fun(newX = X_vw_pred,
                                           Xdesign = X_vw_pred,
                                           newX_pred = BX,
                                           file_path = here::here("Trained Models",
                                                                  file_name),
                                           step_id = mod_names[i],
                                           mod_id = 1,
                                           rseed = 1323,
                                           n_samples = 1e4,
                                           prop_names = properties)

```


```{r}
load(file = here::here("Data",
                       "ss_dat_full.RData"))
in_pr <- c(0.2,0.4,0.6,0.8)

alloys_in <- c("V","W", "VW")
dat_sb <- ss_dat_all%>%
  mutate(W = round(W,1))%>%
  filter(alloy %in% alloys_in,
         W %in% c(0.2,0.5,0.8),
         test_type =="Tension")

ids_in <- X_vw %>%
          mutate(W = round(W,2))%>%
            filter(W %in% c(0.2,0.5,0.8))

gp_mu <- results_bin$gp_mu

gp_mu <- gp_mu%>%
            filter(id %in% ids_in$id)

var_gp <- results_bin$gp_var
var_gp <- var_gp%>%
  filter(id %in% ids_in$id)


```

```{r}
test <- predict_ss_curve_sampling_fun(mu_gp =
                                        as.matrix(gp_mu[,1:3]),
                             var_gp = as.matrix(var_gp[,1:3]),
                             n_log_s = 1e3,
                             n_cond_s = 1e3,
                             max_strain = 0.08)
```



```{r}
dat_ss_ci <- tibble(strain = rep(test$strain, ncol(test$mean)),
                    Ta = rep(ids_in$Ta, each = nrow(test$mean)),
                    W = rep(ids_in$W, each = nrow(test$mean)),
                    pred = as.vector(test$mean),
                    ub = as.vector(test$ub),
                    lb = as.vector(test$lb),
                    )

dat_h <- tibble(W = ids_in$W,
                med = exp(as.vector(gp_mu$log_max_strain) + 
                            qnorm(0.05) * sqrt(as.vector(var_gp$log_max_strain))))
```


##### Stress Strain Curve for Tension

```{r ss_ci, fig.width=6, fig.height=2.5}
dat_ss_ci%>%
  ggplot(aes(x = strain))+
  geom_ribbon(aes(ymax = ub,
                  ymin = lb),
              fill="blue",
              alpha = 0.3)+
  geom_line(aes(y = pred),
            color = "blue",
            linewidth = 1.25)+
  geom_line(aes(x=strain,
                y = stress,
                group = rep),
            data = dat_sb%>%
              filter(strain < 0.08),
            color = "black")+
  facet_wrap(~W,
             scales = "free")+
  labs(y = "Stress",
       x = "Strain",
       title = "Predicted SS Curve for VW Binary Alloys under Tension")+
  theme_bw()
```


#### Coefficients for Tension


```{r}
coefs_ltx <- unname(TeX(c("$\\ln(\\sigma_f)$",
                                  "$\\beta_1$","$\\beta_2$","$\\beta_3$",
                               "$\\beta_4$")))

var_ms_long <- results_bin$gp_var

var_ms_long <- var_ms_long  %>%
            pivot_longer(all_of(properties),
                         values_to = "var",
                         names_to = "property")

pred_ms_t <- results_bin$gp_mu

pred_ms_t <- pred_ms_t%>%
            pivot_longer(all_of(properties),
                         values_to = "pm",
                         names_to = "property")%>%
              mutate(var_ms = var_ms_long$var)%>%
  inner_join(X_vw%>%
               select(V,W,id),
             by = c("id"),
             relationship = "many-to-one")%>%
        mutate(property = factor(property,
                                 levels = properties,
                                 labels = coefs_ltx))

dat_sb3 <- dat_ss_all%>%
  filter(alloy %in% alloys_in,
         type == "t")%>%
  mutate(Training = ifelse(round(V,2) %in% in_pr,"Test","Train"))%>%
            pivot_longer(all_of(properties),
                         values_to = "pm",
                         names_to = "property")%>%
        mutate(property = factor(property,
                                 levels = properties,
                                 labels = coefs_ltx))

```


```{r pred_beta, fig.width=8, fig.height=4}
qz <- qnorm(1-0.05/2)

pred_ms_t%>%
  mutate(lb = pm - qz*sqrt(var_ms),
        ub = pm + qz*sqrt(var_ms))%>%
  ggplot(aes(x= V,
             y = pm))+
  geom_line(linewidth = 1.25,
            colour = "steelblue")+
  geom_ribbon(aes(ymin = lb,
                  ymax = ub,
                  fill = "steelblue"),
              alpha =0.25)+
  geom_point(size = 1.5,
             data = dat_sb3%>%
                    filter(Training == "Train"),
             color = "blue")+
   geom_point(size = 1.5,
             data = dat_sb3%>%
                    filter(Training == "Test"),
             color = "red")+
  facet_wrap(~ property , scales = "free",
             nrow = 2,
             labeller = label_parsed)+
  labs(y = "Value",
       title = TeX("Predicted Coefficients for VW Binaries"))+
  theme(legend.position = "none")
```


